### ISSUE TITLE
Node 8 failing

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/browserify-aes#46]
Seems to be a `tape` issue?

**Comment by dcousens** [comment]
Fails all the way back to even `1.0.0`,  unrelated to recent changes

**Comment by dcousens** [comment]
Appears to have been resolved by `tape`

**Comment by ya7ya** [comment]
@dcousens I'm seeing `invalid key length` error when testing.
```bash
    # some logs to help out debugging
    cipher:  aes-128-ecb  pass:  <Buffer 70 61 73 73 77 6f 72 64>
    config:  { cipher: 'AES',
      key: 128,
      iv: 0,
      mode: 'ECB',
      type: 'block',
      module: { encrypt: [Function], decrypt: [Function] } }

    keys:  { key: <Buffer 5f 4d cc 3b 5a a7 65 d6 1d 83 27 de b8 82 cf 99 2b 95 99 0a 91 51 37 4a bd 8f f8 c5 a7 a0 fe 08 b7 b4 37 2c df bc b3 d1 6a 26 31 b5 9b 50 9e 94 06 12 ... >,
      iv: <Buffer > }

    password before length check  5f4dcc3b5aa765d61d8327deb882cf992b95990a9151374abd8ff8c5a7a0fe08b7b4372cdfbcb3d16a2631b59b509e9406125d0419df9f3d7c6889daf06ae31dc836def08e0af51c40feee3e1f8d9bdf0a4c4cba125486eb2689caa65376392c77c196ad9c3577f64e94fca1361ada2700e9cb1ffd1690474bedbc630ba0bcba

   # Error msg
/browserify-aes/encrypter.js:91
  if (password.length !== config.key / 8) throw new TypeError('invalid key length ' + password.length)
                                          ^

TypeError: invalid key length 128
    at createCipheriv (/media/op/w3/browserify-aes/encrypter.js:91:49)
    at Object.createCipher (/media/op/w3/browserify-aes/encrypter.js:110:10)
    at Test.<anonymous> (/media/op/w3/browserify-aes/test/index.js:26:26)
    at Test.bound [as _cb] (/media/op/w3/browserify-aes/node_modules/tape/lib/test.js:64:32)
    at Test.run (/media/op/w3/browserify-aes/node_modules/tape/lib/test.js:83:10)
    at Test.bound [as run] (/media/op/w3/browserify-aes/node_modules/tape/lib/test.js:64:32)
    at Immediate.next (/media/op/w3/browserify-aes/node_modules/tape/lib/results.js:71:15)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

```

**Comment by dignifiedquire** [comment]
Not sure exactly what broke, but pretty sure the issue is with the latest versions of https://github.com/crypto-browserify/EVP_BytesToKey

Went back to `1.0.0` and things pass, but `1.0.1` and `1.0.2` immediately breaks.

**Comment by dignifiedquire** [comment]
@dcousens fixes are in https://github.com/crypto-browserify/EVP_BytesToKey/pull/13

**Comment by dcousens** [comment]
Why did this only fail in Node 8 though...

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/browserify-aes/pull/50
